from tkinter import *
def click(event):
    text=event.widget.cget("text")
    current_expression = scvalue.get()
    if text=="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text=="C":
        scvalue.set("")
        screen.update()
    elif text=="x":
        if current_expression:
            scvalue.set(current_expression[:-1])
            screen.update()
    else :
        scvalue.set(scvalue.get()+text)
        screen.update()
root=Tk()
root.geometry("400x400")
root.title("calculator")

scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvar=scvalue,font="lucida 25 bold" )
screen.pack(fill=X,pady=10,padx=4,)

f=Frame(root,bg="grey" )
b=Button(f,text="9",font="lucida 18 bold",padx=4,pady=1,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="8",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="7",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="6",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
f.pack()

f=Frame(root,bg="grey")
b=Button(f,text="5",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="4",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="3",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="2",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
f.pack()

f=Frame(root,bg="grey")
b=Button(f,text="1",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="0",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="-",font="lucida 18 bold",padx=6,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="+",font="lucida 18 bold",padx=4,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
f.pack()


f=Frame(root,bg="grey")
b=Button(f,text="*",font="lucida 18 bold",padx=6.1,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="/",font="lucida 18 bold",padx=7,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="%",font="lucida 15 bold",padx=4,pady=6 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="=",font="lucida 18 bold",padx=3.5,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)

f.pack()

f=Frame(root,bg="grey")
b=Button(f,text="C",font="lucida 18 bold",padx=2,pady=1 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text="x",font="lucida 15 bold",padx=7,pady=6 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
b=Button(f,text=".",font="lucida 15 bold",padx=10,pady=6 ,relief="sunken" ,bg="black" ,fg="white")
b.pack(side=LEFT,padx=20,pady=2)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()